### ISSUE TITLE
建议增加虚拟机下载插件

### ISSUE THREAD

**Issue by StrollStars** [Mike-qian/Mydm#1]
因为VMWare虚拟机的官方下载比较麻烦，因此建议增加此插件，如果方便可以把VirtualBox也添加进去，因为VMWare易手之后后续付费策略不清晰。
PS：记得先前有个人人影视的插件，现在下架了吗？

**Comment by Mike-qian** [comment]
人人被净网了所以插件取消了

**Comment by StrollStars** [comment]
谢谢，问个关于种子库的问题，如果链接被迅雷禁止，是不是种子库也没法下载到？

**Comment by Mike-qian** [comment]
> 谢谢，问个关于种子库的问题，如果链接被迅雷禁止，是不是种子库也没法下载到？

这个只是去多个种子库匹配磁链下载种子实际下载迅雷不参与

**Comment by StrollStars** [comment]
有些磁力转种子的网站能够很快下载到种子文件，而下载器通过种子库却一直获取不到，如果不是迅雷参与了，那就是种子库本身就没有。
所以可否搞个专门下载种子的插件？

**Comment by Mike-qian** [comment]
> 有些磁力转种子的网站能够很快下载到种子文件，而下载器通过种子库却一直获取不到，如果不是迅雷参与了，那就是种子库本身就没有。 所以可否搞个专门下载种子的插件？

那是那些种子站本身就缓存有种子不需要去第三方种子库查询，最快速获取种子的方法是dht和tracker模式但国内这个网络情况....

**Comment by StrollStars** [comment]
感谢告知，让dht走代理不太现实。
